name: test
on: [push]
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn tsc -p . --noEmit
      - run: yarn prepare
      - run: yarn test
